### ISSUE TITLE
Precipitation Chance at Night 

### ISSUE THREAD

**Issue by JGKarlin** [cytech/Home-Assistant-wundergroundpws#103]
The value of "precip_chance_1d" changes to "unknown" in the evening and resumes in the morning. I'm wondering if there is a way to get the night time precipitation chance? There does not appear to be an entity for it. It's like the 'precip_chance_1n' is missing and not configurable.

**Comment by attzonko** [comment]
I hit similar issues with Max temperature.  I dug a bit and it is the way the API works, and the app needs to as they say "properly ingest" the data.
![image](https://user-images.githubusercontent.com/4975715/184567127-cbfd0828-133c-436c-87f9-f640e038eb3a.png)

Here is what my high temp history looks like currently:
![image](https://user-images.githubusercontent.com/4975715/184567209-33743193-c00b-4a72-898b-bd6b042b8782.png)

@cytech  Are you going to continue maintaining this integration long term? Are you open to me contributing a fix for this? Or any of the other issues/enhancements?

**Comment by totti4ever** [comment]
Hey, I would definitely be interested as it took me quite a while to figure out why my sensors went unavailable in the afternoon, every single day :-D

I wouldn't be a great help, though. So I would highly appreciate if you were able to get a MR accepted by @cytech!

cheers!

**Comment by cytech** [comment]
added precip_chance_1n  , 2n, 3n, 4n, 5n next release
