### ISSUE TITLE
All entities unavailable

### ISSUE THREAD

**Issue by yuckypants** [cytech/Home-Assistant-wundergroundpws#106]
Found data not updating in Home Assistant. Reset instance, no change. Checked all wunderground entities and all are listed as UNAVAILABLE. 

Error log: 
```
Logger: custom_components.wundergroundpws.sensor
Source: custom_components/wundergroundpws/sensor.py:374
Integration: wundergroundpws (documentation, issues)
First occurred: 11:05:37 AM (6 occurrences)
Last logged: 11:13:23 AM

Check WUndergroupd API ('NO CURRENT RESULT',)
```

To Reproduce
Start home assistant

Expected behavior
Integration starts without error

Desktop (please complete the following information):
Home Assistant 2022.9.4

Integration version: v0.8.1

**Comment by rct** [comment]
Could this be the outage reported in  #105 ?
