### ISSUE TITLE
Showing extra precision on current temperature i.e. 24.6  instead of 24

### ISSUE THREAD

**Issue by gurudc** [cytech/Home-Assistant-wundergroundpws#11]
I was troubled that my temp was an interger, unlike all my other temps which showed as xx.x

The API (https://docs.google.com/document/d/1KGb8bTVYRsNgljnNH67AMhckY8AQT2FVwZ9urj8SWBs/edit) will return only integers unless the parameter numericPrecision=decimal is part of the request.

I made the following change to the sensor.py file 

_RESOURCECURRENT = 'https://api.weather.com/v2/pws/observations/current?stationId={}&format=json&units={}**&numericPrecision=decimal**&apiKey={}'

and I'm now a happy man.  Unaware of any unintended consequences to date.

**Comment by mr-sneezy** [comment]
Excuse my lack of coding knowledge, but do the two pairs of asterisks need to be removed from the line before use ?

**Comment by gurudc** [comment]
> Excuse my lack of coding knowledge, but do the two pairs of asterisks need to be removed from the line before use ?

correct - remove the asterisks

**Comment by alexanderfitu** [comment]
Thanks, this works well.
