### ISSUE TITLE
is_metric deprecated in 2022.11

### ISSUE THREAD

**Issue by figorr** [cytech/Home-Assistant-wundergroundpws#110]
According to the new breaking changes at HAS 2022.11 ...
[https://developers.home-assistant.io/blog/2022/10/14/deprecate-unit-system/](url)

The way they propose to fix it is:

```
if hass.config.units is METRIC_SYSTEM:
    pass

if hass.config.units is US_CUSTOMARY_SYSTEM:
    pass
```
So maybe just updating some lines from of the sensor.py file (lines 353 to 358 ) it could be fixed.

Now they look like

```
if hass.config.units.is_metric:
    unit_system_api = 'm'
    unit_system = 'metric'
else:
     unit_system_api = 'e'
     unit_system = 'imperial'
```
Could be the following change enough?

```
if hass.config.units.is_metric:
    pass
else
    pass
```

**Comment by cytech** [comment]
is_metric is deprecated and should continue to work until HASS 2023.1.
with that said, to get rid of the warning, the fix should be:
change sensor.py

`if hass.config.units.is_metric:`
to
`if hass.config.units is METRIC_SYSTEM:`
and add 
`from homeassistant.util.unit_system import METRIC_SYSTEM`
to imports

**Comment by figorr** [comment]
Thank you.

I just modified the sensor.py as you sugested and the solution works like a charm.
