### ISSUE TITLE
Invalid config for [sensor.wundergroundpws]: [api_key] is an invalid option for [sensor.wundergroundpws]

### ISSUE THREAD

**Issue by convicte** [cytech/Home-Assistant-wundergroundpws#116]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**

Updating to 1.0.0 brings the follow bug preventing the platform from being set up.
The api key is valid (until June 2023) and correctly spaced.
Invalid config for [sensor.wundergroundpws]: [api_key] is an invalid option for [sensor.wundergroundpws]. Check: sensor.wundergroundpws->api_key. (See ?, line ?).

**To Reproduce**
1. Update WPWS to 1.0.0
2. Leave the configuration as is (since it's correct)
3. Restart HA
4. See error - Invalid config for [sensor.wundergroundpws]: [api_key] is an invalid option for [sensor.wundergroundpws]. Check: sensor.wundergroundpws->api_key. (See ?, line ?).

**Expected behavior**

The sensors should be updated and the integration loading correctly.

**Screenshots**

**Comment by riddik14** [comment]
stesso problema, come hai risolto?

**Comment by pollinolas** [comment]
> stesso problema, come hai risolto?

https://github.com/cytech/Home-Assistant-wundergroundpws
