### ISSUE TITLE
The Pressure value in the weather.XXX entity reported incorrectly

### ISSUE THREAD

**Issue by convicte** [cytech/Home-Assistant-wundergroundpws#117]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**

The Pressure value in the weather.XXX entity reported incorrectly while being reported correctly in the sensor from the same station Integration ver. 1.0.0
It seems like the pressure is divided by a 100

**To Reproduce**
1. Go to Developer Tools
2. Select the weather entity generated by WUPWS
3. See error

**Expected behavior**

The atmospheric pressure reported correctly in hPa or any other unit selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/78666770/205284185-6fce7f43-9d3e-46ef-bbbf-5610d7fab1d5.png)

![image](https://user-images.githubusercontent.com/78666770/205285296-18845801-1c52-4f9b-9204-e4d4f11547a5.png)

**Desktop (please complete the following information):**

Win10
Chrome ver.107.0.5304.123

**Comment by cytech** [comment]
fixed v1.0.1

**Comment by convicte** [comment]
Thank you for the immediate response!

**Comment by convicte** [comment]
@cytech - worked like a charm for BP, though the weather entity seems to be unknown in 1.0.1, so I'll have to create a separate ticket

![image](https://user-images.githubusercontent.com/78666770/205314528-ffd1c135-de22-4c34-bb0b-ef588f658aa3.png)

**Comment by cytech** [comment]
seems fine here
try to restart hass

**Comment by convicte** [comment]
I did, twice.

Still the same.

**Comment by cytech** [comment]
wierd. it must exist because it is returning the data
check the settings in the card for entity_id.
also developer tools states for weather.YOUR_STATION_ID.
maybe delete the forecast card and add a new one.

**Comment by convicte** [comment]
It looks like it's related to the actual _1d weather not being populated:
![image](https://user-images.githubusercontent.com/78666770/205321436-0c0130d2-65eb-4bef-9a33-933e4b55dbc2.png)

So I am assuming it will be resolved when it switches to _1n, but I'll report back when it does/doesn't.

FYI, currently the weather card reports blank when I try to use the weather.XXX entity.

**Comment by cytech** [comment]
ok.
when you see something definitive, open a new issue.
thanx

**Comment by cytech** [comment]
just to make sure
also, make sure you deleted the contents on custom_components/wundergroundpws
and copied the new contents of the v1.0.1 zip file back there.
there are a number of other changes in v1.0.1 merged in addition to the pressure issue.
one in particular addresses the weather underground day/night problem.
thanx

**Comment by convicte** [comment]
I've used HACS to update from 1.0.0 to 1.0.1 - do you mean I shouldn't have?

I can also uninstall it and reinstall again, to make sure.

**Comment by cytech** [comment]
yep probably shouldn't have.
I doubt HACS has any knowledge to the existence of v1.X.X.
designed to install manually.
I have not added hacs capability to the v1.X.X repo and do not plan to at this moment.
my next work is going to be to add config_flow and make it a "real" hass integration

**Comment by convicte** [comment]
Then I am a bit confused...
![image](https://user-images.githubusercontent.com/78666770/205327390-536d19fc-8f55-4858-a20a-c11ecd145fcc.png)

I installed it originally from HACS, after removing the 0.8.X branch the same way. 
Both operations worked just fine and the folders were first deleted when uninstalling and correctly populated after I installed 1.0.0.

**Comment by convicte** [comment]
From what I understand, if it hadn't synced it would not know the version either, so it must have.
Ego, it's the latest code there is, but if it doesn't sort itself out, I'll do it manually.

**Comment by cytech** [comment]
https://hacs.xyz/docs/faq/custom_repositories/

**Comment by convicte** [comment]
![image](https://user-images.githubusercontent.com/78666770/205332685-f9b12b90-aa35-419b-ad9b-6900c6c76cf4.png)
Yup, manually added a long time ago.

**Comment by cytech** [comment]
my point being i have not ever integrated HACS to the repo.

> DANGER
Not all repositories will work in HACS, since HACS still needs the repository to have a known structure.

https://hacs.xyz/docs/faq/custom_repositories/

**Comment by rudizl** [comment]
Same behavior of the integration when added manually. After commenting the language string all works as it should.
