### ISSUE TITLE
Unsupported condition string "PM Lgt Rain"

### ISSUE THREAD

**Issue by rudizl** [cytech/Home-Assistant-wundergroundpws#121]
After upgrading to the latest version 1.0.1 the following error occured:

Unsupported condition string "PM Lgt Rain". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

`This error originated from a custom integration.

Logger: custom_components.wundergroundpws.wunderground_data
Source: custom_components/wundergroundpws/wunderground_data.py:205
Integration: Wundergroundpws (documentation, issues)
First occurred: 09:39:08 (10 occurrences)
Last logged: 09:41:09

Unsupported condition string "PM Lgt Rain". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.`

![image](https://user-images.githubusercontent.com/5582186/205430630-9166eff5-f1ad-4a94-a9be-11213997c51b.png)

**Comment by rudizl** [comment]
I've fixed it by adding `"Lgt Rain"` to wunderground_data.py for now.

**Comment by cytech** [comment]
will fix next release
