### ISSUE TITLE
API Login not registered

### ISSUE THREAD

**Issue by whereisocca** [cytech/Home-Assistant-wundergroundpws#13]
Firstly, a huge thank you for developing this.   Great to get integration with the new WUnderground API. 

I haven't been able to successfully get this set up yet, with the high level summary that the sensors do not show up in Home Assistant,  there are no errors I can see from the component, and WUnderground shows that the API hasn't attempted to be logged in (either successfully or unsuccessfully).   I'm doing this on HASSIO on Rpi.

Things I've tried:
1. Updated "load_config = config.load_yaml_config_file('/config/configuration.yaml')" in sensor.py as per other registered issue. 

2. Added additional logging for customer component:
logger:
  logs:
    # log level for a custom component
    custom_components.wundergroundpws: debug

3. Done a lot of research - I really tried to solve this one myself sorry! 

Other information.  The text I currently have in configuration.yaml is:
sensor:
  - platform: wundergroundpws
    api_key: API_KEY_FROM_WEATHERUNDERGROUND
    pws_id: PWS_ID_FROM_WEATHERUNDERGROUND
    monitored_conditions:
      - temp
      - uv

When I check API Key usage on the WEather Underground site,  it shows nothing has occured (i.e not even an attempt to log in). 

When I check the entities in Home Assistant,  no sensors show up. 

When I check Developer Tools / Logs - none of the messages relate to the component (except a message saying the custom integration of Wundergroundpws has not been tested by Home Assistant - I see this as a good sign!). 

Any thoughts on how I debug this.    

Thanks!!

Andrew

**Comment by cytech** [comment]
closed due to inactivity
