### ISSUE TITLE
Unsupported condition string - Please document here for future update

### ISSUE THREAD

**Issue by riddik14** [cytech/Home-Assistant-wundergroundpws#131]
2022-12-09 15:06:05.418 WARNING (MainThread) [custom_components.wundergroundpws.wunderground_data] Unsupported condition string "AM Ice". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

**Comment by cytech** [comment]
noted next release

**Comment by sinner4saints** [comment]
Please add this also:


Logger: custom_components.wundergroundpws.wunderground_data
Source: custom_components/wundergroundpws/wunderground_data.py:207
Integration: Wundergroundpws (documentation, issues)
First occurred: 11:11:19 (6162 occurrences)
Last logged: 19:11:26

Unsupported condition string "PM Snw Shwrs". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "Snow Showers". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "Snow". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "AM Snw Shwrs". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

**Comment by cytech** [comment]
noted next release

**Comment by cytech** [comment]
add "Foggy" to fog condition_map
add "Ice" to snowy condition map
add "Snw Shwrs" to snowy condition map
add "Rn/Snw" to snowy-rainy condition map
add "Iso" to condition_modifiers
noted next release

**Comment by sinner4saints** [comment]
add "Snow Showers" to snowy condition map

**Comment by ruimarinho** [comment]
Another one: 

- `Unsupported condition string "T-Showers"`

**Comment by drjjr2** [comment]
`Unsupported condition string "P Cldy/Wind". `

**Comment by cytech** [comment]
noted next release

**Comment by cytech** [comment]
as a note, after contacting The Weather Company API team for wxPhraseShort list:

> "The wxPhraseShort values are not available to be shared externally.
These strings are possible to be changed, and mapping these strings can lead to issues for client apps in the future."

This means these conditions can change, be added, deleted, etc at any time.
continue to document new ones here, but I will not be doing any special "releases" just for these additions.
I am looking into a different way to get these values in the future.

**Comment by cytech** [comment]
Describe the bug
HA logger is reporting unsupportedconditions strings

Logger: custom_components.wundergroundpws.wunderground_data
Source: custom_components/wundergroundpws/wunderground_data.py:207
Integration: Wundergroundpws ([documentation](https://github.com/cytech/Home-Assistant-wundergroundpws), [issues](https://github.com/cytech/Home-Assistant-wundergroundpws/issues/))
First occurred: 19 December 2022 at 12:40:21 (2330 occurrences)
Last logged: 15:10:30

Unsupported condition string "Drizzle". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "T-Showers". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "PM T-Shwrs". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "Iso T-Storms". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

**Comment by cytech** [comment]
noted next release

**Comment by peterhoe** [comment]
Hi Cytech, noticed the following

This error originated from a custom integration.

Logger: custom_components.wundergroundpws.wunderground_data
Source: custom_components/wundergroundpws/wunderground_data.py:207
Integration: Wundergroundpws (documentation, issues)
First occurred: December 24, 2022 at 04:01:14 (13510 occurrences)
Last logged: 10:03:46

Unsupported condition string "P Cldy/Wind". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "Iso T-Storms". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.
Unsupported condition string "Sunny/Wind". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

**Comment by shtrom** [comment]
Another one: `P Cldy/Wind`

**Comment by clau-bucur** [comment]
Unsupported condition string "Rain/Ice". Please update WUndergroundData.condition_map and/or WUndergroundData.condition_modifiers.

**Comment by clau-bucur** [comment]
Unsupported condition string "Lgt Frz Rain".

**Comment by cytech** [comment]
FIXED
replaced this entire mechanism with iconcode lookup in v1.1.0
https://github.com/cytech/Home-Assistant-wundergroundpws/releases/tag/v1.1.0
