### ISSUE TITLE
Invalid config for [sensor.wundergroundpws]: [api_key]

### ISSUE THREAD

**Issue by unixtall** [cytech/Home-Assistant-wundergroundpws#132]
I have uploaded the integration and there is an error which i dont understand. I didnt changed anything,

**Invalid config for [sensor.wundergroundpws]: [api_key] is an invalid option for [sensor.wundergroundpws]. Check: sensor.wundergroundpws->api_key. (See ?, line ?).**

Do you know about it?

Thanks you.

Home Assistant 2022.12.3
Supervisor 2022.11.2
Operating System 9.3

**Comment by cytech** [comment]
f you are upgrading from v0.8.X to v1.X.X, PLEASE FOLLOW THE README at [V1.X.X UPGRADE](https://github.com/cytech/Home-Assistant-wundergroundpws/blob/v1.X.X/README.md#upgrade).
Particularly if you are installing this as a custom HACS repository.

**Comment by jitteringrunt** [comment]
I am seeing the same problem with a fresh install, where the components never existed prior.  Core version 2022.12.1

**Comment by cytech** [comment]
show me your configuration.yaml
wrap it in a code block so I can see exactly what you have

**Comment by jitteringrunt** [comment]
I was able to sort my issue out.  The documentation did not mention `weather:
  - platform: wundergroundpws  ` section in the latest release.  I dug back through some previous versions and was able to figure out the correct information to include.

`wundergroundpws:
  api_key: KEY
  pws_id: PWS
  numeric_precision: decimal
  
weather:
  - platform: wundergroundpws  

sensor:
  - platform: wundergroundpws
    monitored_conditions:
    ADD CONDITIONS HERE`
