### ISSUE TITLE
Update 2023.1 HA `is_metric` Issue

### ISSUE THREAD

**Issue by maijo366** [cytech/Home-Assistant-wundergroundpws#141]
This in my Logs:

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for wundergroundpws using this method at custom_components/wundergroundpws/sensor.py, line 353: if hass.config.units.is_metric:

**Comment by cytech** [comment]
you need to upgrade wundergroundpws to v0.8.3
or
v1.0.2
