### ISSUE TITLE
Error message reported in log

### ISSUE THREAD

**Issue by MilesAheadToo** [cytech/Home-Assistant-wundergroundpws#144]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
I received the following error message in the log
`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 08:37:43 (1 occurrences)
Last logged: 08:37:43

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for wundergroundpws using this method at custom_components/wundergroundpws/sensor.py, line 353: if hass.config.units.is_metric:`

**To Reproduce**
Error message generated automatically

**Expected behavior**
No error message

**Screenshots**
See error message text above

**Desktop (please complete the following information):**
 - OS: Generic x86-64
 - Browser [e.g. chrome, safari]: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cytech** [comment]
what version of home assistant are you running?
what version of wundergroundpws are you running?

wundergroundpws v0.8.3
v0.8.3: Requires Home Assistant v 2022.11 or later


wundergroundpws v1.1.0
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v1.X.X#installation-prerequisites

**Comment by MilesAheadToo** [comment]
Updated the install, and it seems all OK now. Thanks for the help.

Any thoughts on making the updates more seamless with HACS?
