### ISSUE TITLE
Timout in fresh Docker Home Assistant installation

### ISSUE THREAD

**Issue by Nekronomekron** [cytech/Home-Assistant-wundergroundpws#159]
I tried the latest 1.1.x version also the 2.x.x development version, both with the same result.
While booting, the WundergroundPWS setup is canceled due to a timeout exception.

Environment:
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5

Running in VirtualBox with a Windows Host.

Did a WGET call using the Wunderground URL, within the console in "Studio Code Server" which worked. The generated URL is working (API Key OK, station ID is also OK).

Looks like the python installation is not allowed to do HTTP calls? Is there any configuration I am missing?

[home-assistant.log](https://github.com/cytech/Home-Assistant-wundergroundpws/files/11018762/home-assistant.log)

**Comment by Nekronomekron** [comment]
Found a solution for the problem. The reason for the timeout is, that request from python with the default python user-agent are blocked by Wunderground.

To solve this, just set the user-agent for the request to something different.

Solution for 2.x.x:

Set this in `config_flow.py:44`
`headers = {'Accept-Encoding': 'gzip', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36'}`

**Comment by cytech** [comment]
added v2.0.1
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v2.X.X
