### ISSUE TITLE
- sensor.wupws_weather_1d shows no more data after 15:30h

### ISSUE THREAD

**Issue by Flop2006** [cytech/Home-Assistant-wundergroundpws#16]
After 15:30h - sensor.wupws_weather_1d shows only "unknown" till next day 03:00h
Probably because the one-day-day forecast is right now?
Is it possible to hide the entry if it does not provide any data?

**Comment by cytech** [comment]
after 3:00 pm local time, the api returns 'na' for the value, so that is what gets displayed
