### ISSUE TITLE
Not a bug, but improvement needed - lack option to edit API key in GUI

### ISSUE THREAD

**Issue by nepozs** [cytech/Home-Assistant-wundergroundpws#162]
**Describe the bug**
Not a bug, but improvement needed.

**To Reproduce**
1. Go to Settings -> Devices & Services -> wundergroundpws integration 
2. Click on Setup
3. Lack of option to edit API key 

**Expected behavior**
Possibility to edit should be available, as WU-PWS API key expires every few months.

**Screenshots**
![WU-PWS_no_API-key_edit_2023-04-10_18-11](https://user-images.githubusercontent.com/56661567/230943477-5b197ff5-3942-483a-9205-4347d9372539.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**
API key expires every 6 months, so possibility of change in GUI configuration should be available.

**Comment by nepozs** [comment]
Could you explain what to do if API key expires?

**Comment by Dividing6043** [comment]
My API key expires tomorrow. I cannot find anywhere to manually edit this. In the past I think I have removed and readded the integration, but that seems very clunky. Is there a better way to update the API key?
