### ISSUE TITLE
Warning logs after day0 sensor expiration

### ISSUE THREAD

**Issue by Claudio1L** [cytech/Home-Assistant-wundergroundpws#169]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
Sensor xxxxx_forecast_summary_0d has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: — (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**To Reproduce**
Logs after the day0 sensor expiration

**Expected behavior**
warning Logs not present

**Screenshots**
Sensor xxxxx_forecast_summary_0d has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: — (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Desktop (please complete the following information):**
 - Any

**Smartphone (please complete the following information):**
 - Any
 - 
**Additional context**

**Comment by cytech** [comment]
fixed v2.0.2
