### ISSUE TITLE
Weather forecast for today stays at unknown

### ISSUE THREAD

**Issue by dvine2000** [cytech/Home-Assistant-wundergroundpws#177]
Installed the new 2.x.x. version

The forecast is working only the forcast for today stays at unknown
in the entity expired ( N/A )
sensor_xxxxxx_forecast_summary_0d

I also don't see icons on the forecast with version 1 I saw them.

**Comment by cytech** [comment]
https://github.com/cytech/Home-Assistant-wundergroundpws/issues/97
