### ISSUE TITLE
predictions have invalid date format

### ISSUE THREAD

**Issue by geertvercamer** [cytech/Home-Assistant-wundergroundpws#183]
**predictions have a datetime attribute containing the seconds sinsce 01/01/1970**
This format is not correct, according the official Home Assistant developers documentation it should be UTC Date time in RFC 3339 format: https://developers.home-assistant.io/docs/core/entity/weather/

**To Reproduce**
1. Go to 'Developer Tools / States'
2. Search for 'weaterh.STATIONID'
3. In the right column look for 'predictions'
4. `temperature: 18.4
temperature_unit: °C
humidity: 82
pressure: 1000.44
pressure_unit: hPa
wind_bearing: 51
wind_speed: 2.1
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: rainy
  precipitation: 2.06
  precipitation_probability: 92
  temperature: 20
  templow: 14
  **datetime: 1690434000000**
  wind_bearing: WSW
  wind_speed: 26`

**Expected behavior**
the datetime attribute should be in this format: UTC Date time in RFC 3339

**System:**
 - WUNDERGROUNDPWS V2
 - Home Assistant 2023.7.3
   Supervisor 2023.07.1
   Operating System 10.3
   Frontend 20230705.1 - latest

**Comment by relighted** [comment]
Having the same for reference, this issue is impeding on the use with this excelent weather card.

https://github.com/mlamberts78/weather-chart-card/issues/6?fbclid=IwAR0e0c1iKZXIiKIE6c-yBhrIy8ZTSigFemOHv9anRLGV0GIhAU0FhgP_SDU#issue-1822948991

**Comment by cytech** [comment]
will correct in 2.0.4
although it should not matter because i doubt the weather card you are using will work unless they update
the card for the forecast deprecation warning for 2024.3

**Comment by mlamberts78** [comment]
The card https://github.com/mlamberts78/weather-chart-card/ is updated and supports your version 2.0.4 if the integration now.
