### ISSUE TITLE
State is not correct

### ISSUE THREAD

**Issue by dennidoubles** [cytech/Home-Assistant-wundergroundpws#189]
Suddenly the state of my weather sensor is incorrect, it states `clear-night` , but it is 17:03 o'clock...
Also the forecast shows me a clear-night for tomorrow, during daytime...

What can I do to solve this?

![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/71798417/c1c43f43-ae07-4152-8c3f-6b17cceae4cf)

Wundergroundpws v2.X.X

Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

**Comment by dennidoubles** [comment]
Hopefully you can look into this too, when you have time of course. Thanks @cytech

**Comment by cytech** [comment]
i have no idea why this would happen and can not duplicate.
possible that the API is returning incorrect iconcode??
is it still doing this?

**Comment by Vansmak** [comment]
Same, I'm getting fog all day or clear night. When I look on wunderground site it says mostly sunny under my pws forecast

**Comment by cytech** [comment]
again, these are mapped from the numerous WU API codes returned
https://docs.google.com/document/d/1qpc4QN3YDpGDGGNYVINh7tfeulcZ4fxPSC5f4KzpR_U/edit
to limited set of HASS westher entity condition attributes in wundergroundpws const.py.
so either something is not being refreshed or the API is returning that code (or WU API has changed something and not documented it..)
and as a side note, i don't believe there is an actual Forecast for the pws on the weatherunderground site.
it may be a forecast for the area (latitude/longitude) but not something representative of the API forecast.
