### ISSUE TITLE
Error: Check WUnderground API ('NO CURRENT RESULT',)

### ISSUE THREAD

**Issue by garyak** [cytech/Home-Assistant-wundergroundpws#19]
All sensors generated have become unavailable. HA 105.4. Hass.io on NUC running Docker.CE under Ubuntu.
```
2020-02-17 05:04:42 ERROR (MainThread) [custom_components.wundergroundpws.sensor] Check WUnderground API ('NO CURRENT RESULT',)
2020-02-17 05:06:43 ERROR (MainThread) [custom_components.wundergroundpws.sensor] Check WUnderground API ('NO CURRENT RESULT',)
2020-02-17 05:09:14 ERROR (MainThread) [custom_components.wundergroundpws.sensor] Check WUnderground API ('NO CURRENT RESULT',)
```
repeating every polling cycle. States appear as:

`sensor.wupws_precip_1d | unavailable | restored: true supported_features: 0 unit_of_measurement: in`

**Comment by cytech** [comment]
this seems to be on wundergrounds end.
my station is posting data but station shows offline.
check your station on their website.
i don't know what they are doing to the api but their have been a lot of problems on their end lately
https://apicommunity.wunderground.com/weatherapi

**Comment by rpitera** [comment]
Mine WAS doing that for at least 48 hours but it seems to have corrected itself and started displaying data again sometime late in the day yesterday.  Weirdly, I could pull data manually from their API in REST using Postman, which was really confusing.

But I agree with cytech, this appears to be on WU's end.

**Comment by garyak** [comment]
OK, I'll wait it out. Thanks.

**Comment by garyak** [comment]
Errors due to WU reporting outage.

**Comment by markrennie71** [comment]
I've had this for the last few day and it appears to happened quite frequently. Is this at their end still?
