### ISSUE TITLE
The wundergroundpws integration is using deprecated forecast

### ISSUE THREAD

**Issue by Vlastik123** [cytech/Home-Assistant-wundergroundpws#191]
This has appeared today:

The wundergroundpws integration is using deprecated forecast
This stops working in version 2024.3.0. Please solve it before updating.
The integration wundergroundpws is using the deprecated forecast attribute.

Please report it to the custom integration author..

**Comment by se-wen** [comment]
I got the warning too with the latest HA update 2023.9. Below the Protocol details:

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:339
Integration: Wetter ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 10:24:42 (1 occurrences)
Last logged: 10:24:42

custom_components.wundergroundpws.weather::weather.ialzen26 is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.

**Comment by cytech** [comment]
use bug report template
ignored
