### ISSUE TITLE
 Integration load fails with with deprecation error after updating to 2023.9

### ISSUE THREAD

**Issue by dennidoubles** [cytech/Home-Assistant-wundergroundpws#194]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**The bug**
`weather.xxx` is not working after updating to 2023.9

**Reproduce**
1. Go to Developer Tools
2. fill in `weather.xxx`
3. No state is available
4. Same with the new `weather.get_forecast` service, I cannot select my `weather.xxx` entity and when I fill it in by hand, I get an error.
5. The error is: Failed to call service `weather.get_forecast`. Entity `weather.xxx` does not support this service.

**Expected behavior**
Because of the way to receive forecasts via this Service, I expect to receive the possibility to create my own daily/hourly forecast

**Screenshots**
N.A.

**Desktop (please complete the following information):**
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest
Home-Assistant-Wundergroundpws v2.X.X

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cytech** [comment]
update to v2.0.3 to fix the integration load failure
this does not address the new get forecast service or the deprecation error

**Comment by Trebacz** [comment]
@cytech  Updated to v2.0.3. I can confirm the integration now loads fine on 2023.9. Thank you for the quick turn around!. Great integration by the way...

**Comment by dennidoubles** [comment]
> update to v2.0.3 to fix the integration load failure this does not address the new get forecast service or the deprecation error

Thank you so much! I can confirm it is working again, perfect.

**Comment by mitch55500** [comment]
@cytech, 
I already your latest version.

![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/31507239/b9f85b7e-ac1c-4847-b662-a41459344d4b)

**Comment by Mattia2399** [comment]
I updated to v2.0.3 but still get the deprecation error

**Comment by cytech** [comment]
its a warning
ignore it
it will continue to work until  March of 2024
i will get around to fixing it before then...

**Comment by kimbo1st** [comment]
For me it stopped working and see this in the log:

`Logger: homeassistant.components.weather
Source: custom_components/wundergroundpws/weather.py:138 
Integration: Weer (documentation, issues) 
First occurred: 7 september 2023 om 23:45:54 (18 occurrences) 
Last logged: 19:43:12

Error adding entities for domain weather with platform wundergroundpws
Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 722, in state_attributes
    if (visibility := self.native_visibility) is not None:
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/weather.py", line 138, in native_visibility
    return self._attr_visibility
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WUWeather' object has no attribute '_attr_visibility'
/`

**Comment by cytech** [comment]
again..
failure to load was not caused by this deprecation
actual failure was non-existent _attr_visibility property
update to v2.0.3
this does not address the deprecation error and you will continue to get the message until i get around to fixing it before 2024.3...
"this is deprecated and will be unsupported from Home Assistant 2024.3"

**Comment by kimbo1st** [comment]
I still seem to have the issue.. API is ok and still valid.
How do I know I’m using the update 2.0.3? Do I manually update? How? Thx

**Comment by MuzWestlake** [comment]
> I still seem to have the issue.. API is ok and still valid. How do I know I’m using the update 2.0.3? Do I manually update? How? Thx

@kimbo1st unless you have manually updated (i.e. copied the latest custom components files to your HA - see https://github.com/cytech/Home-Assistant-wundergroundpws#installation), then you are most likely not running 2.0.3. 

Installing 2.0.3 fixed my issues with forecast not working. 

As for the warning message "this is deprecated and will be unsupported from Home Assistant 2024.3", in HA, you can simply click 'ignore' to hide this until this is fixed, without issue. 

Thanks @cytech for your work on this, much appreciated.

**Comment by cytech** [comment]
deprecation fix
upgrade to v2.0.4
