### ISSUE TITLE
wundergroundpws integration uses outdated forecasts

### ISSUE THREAD

**Issue by mitch55500** [cytech/Home-Assistant-wundergroundpws#195]
Here is the warning I have on my Home assistant : 

`custom_components.wundergroundpws.weather::weather.**** is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.`

Just for inform @cytech.

My system : 
![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/31507239/c2e57bfb-35d2-4494-94f3-3df53c7bcbe7)

**Comment by kimbo1st** [comment]
Idem dito

**Comment by cytech** [comment]
see issue #194

**Comment by mitch55500** [comment]
I already use this version (v. 2.0.3)

![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/31507239/7ee74ed6-0a23-43f9-8f0e-edbde3d829bb)

**Comment by cytech** [comment]
and is the integration working?
if so, then ignore the warning.
it is a deprecation warning that will be there until I get around to addressing it BEFORE 2024.3

**Comment by mitch55500** [comment]
It works, yes.

This notification suggests that there is a problem.

![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/31507239/fba8220b-a51b-4f6b-bab1-37d85e92d559)

**Comment by cytech** [comment]
it will be a problem in March of 2024, 6 months from now
