### ISSUE TITLE
The wundergroundpws integration is using deprecated forecast

### ISSUE THREAD

**Issue by Bragesson** [cytech/Home-Assistant-wundergroundpws#197]
Integration stop working in latest Home Assistant
 Home Assistant 2023.9.0 Supervisor 2023.08.3 Operating System 10.5 Frontend-version: 20230906.1 - latest 

The integration wundergroundpws is using the deprecated forecast attribute.

Please report it to the custom integration author..

**Comment by Bragesson** [comment]
Sorry! I se the solution...

**Comment by dyeadon** [comment]
What is the Solution?

**Comment by cytech** [comment]
see issue #194

**Comment by dyeadon** [comment]
Thanks
