### ISSUE TITLE
Add wundergroundpws to weather domain

### ISSUE THREAD

**Issue by garyak** [cytech/Home-Assistant-wundergroundpws#2]
I have this running to. The native weather forecast card requirement:
"This card works only with platforms that define a weather entity. "
weather.wundergroundpws
Could sensor.py be modified to conform to this requirement?

**Comment by totti4ever** [comment]
Any chance of this being implemented?

**Comment by RJ-Make** [comment]
First Off, A big thank you to all the contributors. I would also love to see this implemented.

**Comment by totti4ever** [comment]
For the meantime look @ #95

**Comment by cytech** [comment]
see v1.0.0
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v1.X.X
