### ISSUE TITLE
Forecast Summary Today Expired not being refreshed

### ISSUE THREAD

**Issue by MichaelRV82** [cytech/Home-Assistant-wundergroundpws#202]
The sensor.STATIONID_forecast_summary_0d is being set to expire after 3 PM as expected but is not being refreshed next day. It keeps the Expired Status only after disabling and re-enabling the entity this is solved.

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

**Comment by cytech** [comment]
use bug report template
not enough info to duplicate and no other reports
what version of the integration?
etc.
