### ISSUE TITLE
error creating sensors and labels missing

### ISSUE THREAD

**Issue by royvanmanen** [cytech/Home-Assistant-wundergroundpws#209]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
1. labels missing on screens (setting on NL)
2. After installation sensors are not generated.

error in logs:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:367
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:21:56 (4 occurrences)
Last logged: 16:18:50

Error while setting up wundergroundpws platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 582, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/wundergroundpws/sensor.py", line 130, in name
    self.entity_description.key in self.coordinator._tranfile[FIELD_DAYPART].keys():
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'daypart'

A clear and concise description of what the bug is.

**To Reproduce**
- downloaded 2.04 (no previous install on system) en copied wundergroundpws folder to custom_components folder (upload via vs_code)
- reboot HA
- add integration
- configure -> result success, data is fetched from wunderground
**Expected behavior**
a bunch of sensors I can use

**Screenshots**
![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/6940161/a2e1ed63-5fb0-4bfe-9684-2b5095b9cca9)

In first time config I guessed which field was api key and station_id. Labels missing there also.
** HA version 2023.10.1
HAOS 10.5

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari]: Chrome and Edge same behavior
 - Version [e.g. 22] newest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Google Pixel 6
 - OS: [e.g. iOS8.1] Android 
 - Browser [e.g. stock browser, safari] HA-app, chrome same behavior
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by cytech** [comment]
https://github.com/cytech/Home-Assistant-wundergroundpws#configure

**Comment by royvanmanen** [comment]
There are no sensors created that I can enable because 1. I see no labels and 2. they are not created due to an error (see my text).
The printscreen in this issue is all I see when clicking configure. And when I click add item this is what it looks like (looks like add weather station id and api key but no labels so not sure what to do):
![image](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/6940161/4f00f92b-3a50-496d-ab0a-ceb908c2879b)

**Comment by cytech** [comment]
string translation issue i guess.here is what they should look like (and it should still work ..)
![Screenshot from 2023-10-08 13-09-19](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/7809634/f3065722-6ff8-40fa-a967-46897c0ff5a6)
![Screenshot from 2023-10-08 13-10-02](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/7809634/4c80f023-1f1c-42b0-b6d0-7c4b5467ee45)

**Comment by cytech** [comment]
cannot duplicate in hass 2023.12
should default to english text as above
