### ISSUE TITLE
Bringing wundergroundpws to HACS 

### ISSUE THREAD

**Issue by upwindanderl** [cytech/Home-Assistant-wundergroundpws#21]
I needed at least 10hs to recognize that the original wunderground integration is obsolete and this awesome creation works well instead.

So
I guess there are a few more poor guys outside 
Isn't it possible to change the original integration with this one?!
**Or at least it would be soo so so cool to have wundergroundpws in HACS.**

**Comment by upwindanderl** [comment]
SO SORRY! 


few minutes ago i learned how to suit up own custom integrations into hacs.
So easy and i didn't know that.

If your'e troubling the same, goto hacs -> settings -> add custom repositories ( https://github.com/cytech/Home-Assistant-wundergroundpws )
so easy and your always up to date

**Comment by rudibarani** [comment]
Thanks for this hint. I have just switched to Home Assistant and finding my ways around. It could be helpful for others to mention this possibility directly on the default page.
