### ISSUE TITLE
"Forecast Summary Today Expired" (unknown) 0d

### ISSUE THREAD

**Issue by RJ-Make** [cytech/Home-Assistant-wundergroundpws#218]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
I upgraded to version 2.0.4 from 1.xx. and ever since I can't get many of the 0d forecasts to provide data. The entities have (Example: "Forecast Summary Today Expired" (unknown)  SEE screenshot below.

**To Reproduce**
1. Go to 'Integration'
2. Click on 'Entities'
3. Search for 'Today' 

**Expected behavior**
Updated data to be provided by the 0d entities. 

**Screenshots**

![2023-12-17_17-19-56](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/8496835/0207c86d-ee3a-4888-ae34-c898ff06d2b2)

**Desktop (please complete the following information):**
 - Browser [Chrome, Firefox]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [NA]
 - OS: [NA]
 - Browser [NA]
 - Version [NA]

**Comment by cytech** [comment]
the 0d forecasts will not provide data after 3:00pm local time
give it 24 hours and see if it resolves itself
also, there is no direct upgrade from v1 to v2 so unless you have followed the install instructions you may have issues
https://github.com/cytech/Home-Assistant-wundergroundpws?tab=readme-ov-file#installation-prerequisites
https://github.com/cytech/Home-Assistant-wundergroundpws?tab=readme-ov-file#upgrade

**Comment by RJ-Make** [comment]
I used the wrong word, I completely removed V1 and started from scratch with V2. Twice now. 

The problem never resolves. The only 0d entity that works reliably is 0d Temperature.

**Comment by cytech** [comment]
i dont know what to tell you. i cannot reproduce it.
if you cant get it to work maybe get rid of the integration and go with a rest sensor like these guys
https://github.com/cytech/Home-Assistant-wundergroundpws/discussions/213
