### ISSUE TITLE
Help needed with Hassio set up

### ISSUE THREAD

**Issue by philm142** [cytech/Home-Assistant-wundergroundpws#22]
Sorry I've tried to sort this myself, but I can't work out where I'm going wrong. I have cut and pasted the configuration.yaml entry as supplied and put my api key and pws_id in the top two lines as requested, and left everything else as is. But when I check my configuration.yaml is says: 
Error loading /config/configuration.yaml: mapping values are not allowed here
  in "/config/configuration.yaml", line 107, column 14
line 107 is:
  description: The API key for Weather Underground. See above for details.
where am I going wrong, is there a idiot's guide

**Comment by BeardedTinker** [comment]
Have the same issue - it was working up until now. Had to restore from backup and now when I press on check configuration, it just spins and doesn't give OK or error. Since configuration check can't complete, I can't also restart HA.
Pulled latest version of github just to be sure.

**Comment by philm142** [comment]
I never got it to work, I couldn't get past the config check. I tried all sorts and used a yaml checker online, which said it was fine, but Home assistant didn't like it, but only with the files in the custom components folder. I even removed everything other than the first four lines and that did the same. The only thing I can think of is the latest version of HA doesn't like it.

**Comment by cytech** [comment]
there is a bug with the addon and hassio
you need to modify the config path in the addon
see issue #1
Error Configuration.yaml not in default directory
#1

**Comment by philm142** [comment]
Brilliant, works perfectly now, thank you for all your help

**Comment by cytech** [comment]
see issue #46
