### ISSUE TITLE
ERROR (MainThread) [homeassistant.components.wunderground.sensor]

### ISSUE THREAD

**Issue by Asom-Velz** [cytech/Home-Assistant-wundergroundpws#23]
Hi I try to setup the Wunderground as per your instructions I put my API key and PWS id 
but I receve the following 

error2020-06-10 13:58:09 ERROR (MainThread) [homeassistant.components.wunderground.sensor] Error fetching WUnderground data: ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='http://api.wunderground.com/api/###MyAPI_Key###/alerts/almanac/conditions/forecast/lang:EN/q/pws:##MyPWSID##.json")

configuration.yaml
sencor:
- platform: wunderground
  api_key: ###MyAPI_Key###
  pws_id: ##MyPWSID##
  monitored_conditions:
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_1d_kph
      - alerts
********************************************************************************
WU Member API Keys
Your API Key
###MyAPI_Key###
Expires: Sun, 15 Nov 2020 20:26:07 GMT

**Comment by Asom-Velz** [comment]
Hi again,

I made a clean install and configured only wundergroundpws.

When I run Configuration Validation the wheel it spins for ever.
After reboot It does not working :( and I have the attached errors
In order to be sure I have tested also putting the apikey and pwsid directly in the config and not in secret.

When I remove the wundergroundpws settings from the congig HA works ok.

Any idea what I not doing ok ?

[configuration.yaml.txt](https://github.com/cytech/Home-Assistant-wundergroundpws/files/4769044/configuration.yaml.txt)
[Error Log.txt](https://github.com/cytech/Home-Assistant-wundergroundpws/files/4769049/Error.Log.txt)
![Error#01](https://user-images.githubusercontent.com/65943619/84471016-2a674a80-ac8d-11ea-8c0c-0643a09730a0.jpg)
![ConfigValid](https://user-images.githubusercontent.com/65943619/84471025-2dfad180-ac8d-11ea-9c95-90be05b4162e.jpg)
![WU_apikey_Usage](https://user-images.githubusercontent.com/65943619/84471028-30f5c200-ac8d-11ea-85b8-492600c0ffe6.jpg)

**Comment by cytech** [comment]
are you running Hassio?
if so there is an issue with the custom integration finding the config directory.
refer to this issue:
Error Configuration.yaml not in default directory #1
#1

**Comment by Asom-Velz** [comment]
Hi again

Problem solved after i put at  sensor.py '/config/configuration.yaml'. 

![WU UP and Running](https://user-images.githubusercontent.com/65943619/84533115-2a4c6680-acf0-11ea-98ae-569234c56648.jpg)

Thank you a lot for your help and the wonderful job with this repo

**Comment by cytech** [comment]
you're welcome

**Comment by Asom-Velz** [comment]
Beer send have fun :+1:
