### ISSUE TITLE
Error loading integration after restarting HA

### ISSUE THREAD

**Issue by figorr** [cytech/Home-Assistant-wundergroundpws#233]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**

**To Reproduce**
1. Restart HA

**Expected behavior**
Every time I restart HA due to any HA update ... the integration didn't start. A manual reload solves the problem until the next HA restart.

**Desktop (please complete the following information):**
 - HA OS 2024.2.2, but I had this issue since 2024.2

**Additional context**
From the logs.

Message 1:
> Logger: homeassistant.components.weather
> Source: helpers/entity_platform.py:352
> Integration: Clima (documentation, issues)
> First occurred: 17:52:33 (1 occurrences)
> Last logged: 17:52:33
> 
> Error while setting up wundergroundpws platform for weather
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1000, in state
>     return self.condition
>            ^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
>     day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
>     return self.data[FIELD_DAYPART][0][field][period]
>            ~~~~~~~~~^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object is not subscriptable

Message 2

> Logger: homeassistant.components.weather
> Source: helpers/entity_platform.py:533
> Integration: Clima (documentation, issues)
> First occurred: 17:52:33 (1 occurrences)
> Last logged: 17:52:33
> 
> Error adding entities for domain weather with platform wundergroundpws
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
>     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
>                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1000, in state
>     return self.condition
>            ^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/weather.py", line 163, in condition
>     day = self.coordinator.get_forecast(FIELD_FORECAST_ICONCODE)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/coordinator.py", line 214, in get_forecast
>     return self.data[FIELD_DAYPART][0][field][period]
>            ~~~~~~~~~^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object is not subscriptable

Message 3

> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:344
> Integration: Sensor (documentation, issues)
> First occurred: 17:52:33 (1 occurrences)
> Last logged: 17:52:33
> 
> Error while setting up wundergroundpws platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/wundergroundpws/sensor.py", line 47, in async_setup_entry
>     WundergroundPWSSensor(coordinator, description) for description in SENSOR_DESCRIPTIONS
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/sensor.py", line 116, in __init__
>     self._sensor_data = _get_sensor_data(
>                         ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wundergroundpws/sensor.py", line 180, in _get_sensor_data
>     return sensors[FIELD_OBSERVATIONS][0][kind]
>            ~~~~~~~^^^^^^^^^^^^^^^^^^^^
> TypeError: 'NoneType' object is not subscriptable

**Comment by RSlegt** [comment]
I have the same issue, I first restored HA 2024.1.6 to get this working again. 
Thanks figorr for letting me know it can also be temporary solved by reloading Wundergroundwps integration.
Hope a fix will be there soon.

**Comment by figorr** [comment]
> I have the same issue, I first restored HA 2024.1.6 to get this working again. Thanks figorr for letting me know it can also be temporary solved by reloading Wundergroundwps integration. Hope a fix will be there soon.

Until it is solved … I created an automation in order to reload the integration once HA is restarted. So I don’t have to manually reload it, because sometimes I absolute forgot it.

The service to use is “homeassistant.reload_config_entry”. To setup this service you must use the “entry_id” of the integration. You can find this “entry_id” in the file “core.config.entities” file located in the .storage folder.

**Comment by RSlegt** [comment]
> > I have the same issue, I first restored HA 2024.1.6 to get this working again. Thanks figorr for letting me know it can also be temporary solved by reloading Wundergroundwps integration. Hope a fix will be there soon.
> 
> Until it is solved … I created an automation in order to reload the integration once HA is restarted. So I don’t have to manually reload it, because sometimes I absolute forgot it.
> 
> The service to use is “homeassistant.reload_config_entry”. To setup this service you must use the “entry_id” of the integration. You can find this “entry_id” in the file “core.config.entities” file located in the .storage folder.

I was doing the same ;-) 

This automation seems to be a workaround:

alias: Wundergroundwps reload
description: ""
trigger:
  - platform: state
    entity_id: weather.<station_id>
    to: unavailable
condition: []
action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: weather.<station_id>
    data: {}
mode: single

**Comment by norburban** [comment]
> > > I have the same issue, I first restored HA 2024.1.6 to get this working again. Thanks figorr for letting me know it can also be temporary solved by reloading Wundergroundwps integration. Hope a fix will be there soon.
> > 
> > 
> > Until it is solved … I created an automation in order to reload the integration once HA is restarted. So I don’t have to manually reload it, because sometimes I absolute forgot it.
> > The service to use is “homeassistant.reload_config_entry”. To setup this service you must use the “entry_id” of the integration. You can find this “entry_id” in the file “core.config.entities” file located in the .storage folder.
> 
> I was doing the same ;-)
> 
> This automation seems to be a workaround:
> 
> ```
> alias: Wundergroundwps reload
> description: ""
> trigger:
>   - platform: state
>     entity_id: weather.<station_id>
>     to: unavailable
> condition: []
> action:
>   - service: homeassistant.reload_config_entry
>     target:
>       entity_id: weather.<station_id>
>     data: {}
> mode: single
> ```

Thank you!

**Comment by cytech** [comment]
update to v2.0.6
Starting with home assistant 2024, rest availability on Home Assistant Operating System (on Raspberry Pi ?) after restart is delayed and causing setup failure.
If you still get a WUPWS setup error after restarting Home Assistant, you can try and change the DEFAULT_TIMEOUT in const.py to 60 seconds.
