### ISSUE TITLE
Today's forecast returning "unknown"

### ISSUE THREAD

**Issue by chansters** [cytech/Home-Assistant-wundergroundpws#24]
My "sensor.wupws_weather_1d" sensor is always showing "unknown".  But the 1n, 2d, 2n etc sensors are all working.

**Comment by cytech** [comment]
this happens after 3:00 pm
wunderground stops reporting current day after 3 pm

**Comment by chansters** [comment]
Thank you ! I was setting this up at night and I checked, and you're right, the "1d" forecast is now showing. Thank you for clarifying.
