### ISSUE TITLE
Can not add integration

### ISSUE THREAD

**Issue by proasnet** [cytech/Home-Assistant-wundergroundpws#245]
IF YOU ARE NOT REPORTING A REPRODUCIBLE BUG, PLEASE USE DISCUSSIONS
**Describe the bug**
After registering at wunderground.com, add a station, get API and Station ID, the form for add integration return Invalid Station ID.
I am trying next formats:
```
ID:XXXXXXX,KEY:********
I tried
ID:XXXXXXX
XXXXXXX
ID:XXXXXXX,KEY:********
```

**To Reproduce**
1. Go to 'Add Integration'
2. Click on 'Sundergroundpws'
3. Enter API
4. Enter Station ID
5. Press Send
6. See error Invalid Station ID

**Expected behavior**
Go to next configuration step

**Screenshots**
![obrazek](https://github.com/cytech/Home-Assistant-wundergroundpws/assets/76579362/6144e4a0-559f-4568-8eee-5ef1f5198b19)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 125.0.2

**Smartphone (please complete the following information):**
 - Device: Samsung A12
 - OS: Android
 - Browser Opera

**Additional context**
Without filling in the Station ID in the correct form, it is not possible to continue with the configuration. I tried possible combinations, all by copying from wunderground.com, case sensitive.

**Comment by cytech** [comment]
again, not an issue
you need to input the APIKEY (32 DIGIT KEY IN YOUR WUNDERGROUND DASHBOARD) NOT THE STATION KEY (8 DIGIT).
the station id (name) should be the same as in your device list and i believe it is usually all capitals.
so in the API Key input paste the 32 digit API KEY (XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX),
in the Personal weather Station id enter the station name  (KXXXXXXX1)
