### ISSUE TITLE
Question / Enhancement : One liner weather forecast

### ISSUE THREAD

**Issue by chansters** [cytech/Home-Assistant-wundergroundpws#25]
Is there a way to get this "one liner" weather forecast ?  I love it for its simplicity. 

<img width="262" alt="San Francisco, CA Weather Conditions | Weather Underground 2020-06-30 13-33-58" src="https://user-images.githubusercontent.com/8441205/86174431-7a8c3c80-bad6-11ea-85c4-50ce1326fe5c.png">

**Comment by cytech** [comment]
nope

**Comment by cytech** [comment]
closed due to inactivity
