### ISSUE TITLE
WUNDERGROUNDPWS Integration breaks when HA upgrade to 0.92

### ISSUE THREAD

**Issue by macfarlaneb** [cytech/Home-Assistant-wundergroundpws#3]
I've noticed that the integration breaks when HA is upgraded to 0.92. When code checking, it errors with: "Integration wundergroundpws not found when trying to verify its sensor platform."

To fix this:
1. Create a blank file: `/config/custom_components/wundergroundpws/__init__.py`
2. Create a new file: `/config/custom_components/wundergroundpws/manifest.json` with the contents:

{
"domain": "wundergroundpws",
"name": "Weather Underground (APIv2)",
"documentation": "https://github.com/cytech/Home-Assistant-wundergroundpws",
"dependencies": [],
"codeowners": [],
"requirements": []
}

**Comment by cytech** [comment]
thank you
added to branch master
