### ISSUE TITLE
wundergroundpws sensors report unavailable

### ISSUE THREAD

**Issue by garyak** [cytech/Home-Assistant-wundergroundpws#31]
Environment:

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Ubuntu 18.04.5 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.0-42-generic
python_version | 3.8.3
supervisor | 235
timezone | America/Denver
version | 0.114.2
virtualenv | false

All wundergroundpws sensor started reporting unavailable today. I contacted WU/IBM to see if their API was down, but the [URL](https://api.weather.com/v3/wx/forecast/daily/5day?geocode={},{}&units={}&{}&format=json&apiKey={}) returns current data.

**Comment by cytech** [comment]
goto the wunderground site and look at your pws
shows offline??

**Comment by garyak** [comment]
Yes. WU is unavailable. Ambient shows I'm reporting. Must be WU.

**Comment by cytech** [comment]
same here. again......
