### ISSUE TITLE
Is it possible to put the Alert sensor?

### ISSUE THREAD

**Issue by Usura666** [cytech/Home-Assistant-wundergroundpws#41]
Hi, as the title suggests I am wondering if there is a way to integrate the Allert sensor.
 It's possible to do it?

**Comment by cytech** [comment]
The weatherunderground personal weather station api is pretty basic and only serves up info on your station.
a weather underground alert is not published.
so short answer is no.
if you mean to have HA alert you when the temperature = 80 (for example), you would have to create something.

**Comment by Usura666** [comment]
No, I'm not talking about automation.
 I had noticed that by configuring the Wu widget with my weather station, alerts are issued.  I was hoping there was a way to get them on Ha too.
 Anyway thanks.  I am file and have managed to configure everything!
