### ISSUE TITLE
Add decimals to temperature

### ISSUE THREAD

**Issue by bochelork** [cytech/Home-Assistant-wundergroundpws#42]
Add : `&numericPrecision=decimal` to the link to get decimals in temperature in sensor.py line 30: 

`_RESOURCECURRENT = 'https://api.weather.com/v2/pws/observations/current?stationId={}&format=json&numericPrecision=decimal&units={}&apiKey={}'`

**Comment by bochelork** [comment]
I see there is a pull request from 2019, but it's still not in sensor.py

**Comment by cytech** [comment]
when i get around to it i will make this a configuration item for those of us who do not care about degree decimal.
in the mean time, if you need this, modify your local  version of sensor.py.
thanx
