### ISSUE TITLE
Invalid config and hang on NON Home Assistant Core Installations

### ISSUE THREAD

**Issue by cytech** [cytech/Home-Assistant-wundergroundpws#46]
I created this to work with my Home Assistant Setup which is Home Assistant Core in a venv on a Raspberry Pi.
This fails on other types of Home Assistant installations. Per issues reported (issue  #1 ), you will need to modify the sensor.py for these other installation types.

**Home Assistant Operating System:**

   edit sensor.py in custom_components/wundergroundpws and change line 46 from

`      load_config = config.load_yaml_config_file(conf_file)
`   
to

`      load_config = config.load_yaml_config_file('/home/homeassistant/configuration.yaml')
`

**Home Assistant Container (Hass.IO):**

   edit sensor.py in custom_components/wundergroundpws and change line 46 from

`      load_config = config.load_yaml_config_file(conf_file)
`   
to

`      load_config = config.load_yaml_config_file('/config/configuration.yaml')
`

**Home Assistant Supervised:**

???

See updated README.md

**Comment by cytech** [comment]
fixed with PR#50

**Comment by fun4stuff** [comment]
I am running g home assistant in a docker container. I do not have any line with 'load_config' in my sensor.pay file.
