### ISSUE TITLE
Hassio installation

### ISSUE THREAD

**Issue by Grey-Lancaster** [cytech/Home-Assistant-wundergroundpws#5]
I cannot find any path similar to what is suggested to copy the files to.
Only tool I have available is the configurator from the dashboard in hassio on a Pi3 

Any kind soul willing to help :)
Thanks,
Grey

To Install, copy the custom_components directory into your .homeassistant directory and the www directory into your .homeassistant directory.

or

copy the contents of the custom_components into an existing custom_components directory in your .homeassistant directory and the contents of the www directory into an existing www directory in your .homeassistant directory.

**Comment by Grey-Lancaster** [comment]
Okay, geez 

from the code page https://github.com/cytech/Home-Assistant-wundergroundpws
click clone or download.  Download as a zip to your pc and unzip it

In Hassio on a pi install the addon to the dashboard called configurator 
It will probably open to configuration.yaml on default. click the folder at the top and i should be in the config/ folder
click make new folder at the top and create custom_components
open that folder and make a folder wundergroundpws
Open that folder and click upload file
find the files you unzipped, There should be 4 files to upload
then clicksensor.py on the left it will open on the right.  clcik on the right and change line 45 to
`load_config = config.load_yaml_config_file('/config/configuration.yaml')`
click the save button at the top right

now hit the folder button at the top and go back to config/
make a new folder www
in www make a folder wupws_icons
go to the icons folder and upload the 40 something icons.  Pain doing them one at a time

click the folder at the top and o back to config/
click on configuration.yaml

copy and paste

`# Sensors
sensor:
  # Weather prediction
  - platform: yr

  - platform: wundergroundpws
    api_key: your key
    pws_id: your id

    monitored_conditions:
    - humidity
    - temp
    - dewpt
    - heatIndex
    - windChill
    - precipRate
    - precipTotal
    - pressure
    - windGust
    - windSpeed
    - weather_1d
    - weather_1n
    - weather_2d
   - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
   - weather_4n
   - weather_5d
   - weather_5n
    - temp_high_1d
    - temp_low_1d
    - wind_1d
    - precip_1d
    - precip_chance_1d

group:
  daily_forecast:
    name: Daily Forecast
    entities:
      - sensor.wupws_temp
      - sensor.wupws_weather_1n
      - sensor.wupws_weather_2d
      - sensor.wupws_weather_2n
      - sensor.wupws_weather_3d
      - sensor.wupws_weather_3n
      - sensor.wupws_weather_4d
      - sensor.wupws_weather_4n
`

notice the readme is wrong it is sensor.wups as I have it here

save the file
hassio dashboar >system>reboot

Best,
Gramps

**Comment by cytech** [comment]
piece of cake..  :)
thanx

**Comment by Grey-Lancaster** [comment]
you can get access to all the different sensors available and the format starting here from your json file
https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

Just for folks pondering :)

**Comment by dolenec** [comment]
> 
> 
> Okay, geez
> 
> from the code page https://github.com/cytech/Home-Assistant-wundergroundpws
> click clone or download. Download as a zip to your pc and unzip it
> 
> In Hassio on a pi install the addon to the dashboard called configurator
> It will probably open to configuration.yaml on default. click the folder at the top and i should be in the config/ folder
> click make new folder at the top and create custom_components
> open that folder and make a folder wundergroundpws
> Open that folder and click upload file
> find the files you unzipped, There should be 4 files to upload
> then clicksensor.py on the left it will open on the right. clcik on the right and change line 45 to
> `load_config = config.load_yaml_config_file('/config/configuration.yaml')`
> click the save button at the top right
> 
> now hit the folder button at the top and go back to config/
> make a new folder www
> in www make a folder wupws_icons
> go to the icons folder and upload the 40 something icons. Pain doing them one at a time
> 
> click the folder at the top and o back to config/
> click on configuration.yaml
> 
> no clue why i cant paste properly but other post show the top part
> 
> group:
> daily_forecast:
> name: Daily Forecast
> entities:
> - sensor.wupws_temp
> - sensor.wupws_weather_1n
> - sensor.wupws_weather_2d
> - sensor.wupws_weather_2n
> - sensor.wupws_weather_3d
> - sensor.wupws_weather_3n
> - sensor.wupws_weather_4d
> - sensor.wupws_weather_4n
> 
> > 
> 
> notice the readme is wrong it is sensor.wups as I have it here
> 
> save the file
> hassio dashboard >system>reboot
> 
> Best,
> Gramps

Thank you... Your instruction help me - now it's working..

But one question... If we know that we can have 1500 requests / day - so we can make request every minute, or better every 57,6 seconds...
Where can we change request interval?

**Comment by cytech** [comment]
i think you can try and modify line 39 in wunderground.py
MIN_TIME_BETWEEN_UPDATES = timedelta(minutes=5)

**Comment by dolenec** [comment]
Yes.. I did change it.. All working fine.. thank you..

**Comment by cytech** [comment]
see issue #46
