### ISSUE TITLE
5.png

### ISSUE THREAD

**Issue by jdeath** [cytech/Home-Assistant-wundergroundpws#51]
Just started using and updated to after your #50 commit. One of my icons was not loading correctly:
`friendly_name: Saturday
icon: 'mdi:gauge'
entity_picture: /local/wupws_icons/5.png`

I copied 05.png to 5.png and it displays correctly.

**Comment by cytech** [comment]
strange...
what platform/OS are you running?

**Comment by jdeath** [comment]
Version core-2021.2.3
Installation Type Home Assistant Supervised
Development false
Supervisor true
Docker true
Virtual Environment false
Python Version 3.8.7
Operating System Family Linux
Operating System Version 4.19.0-13-amd64
CPU Architecture x86_64

**Comment by cytech** [comment]
i thought i fixed that.
I guess it will happen for all the "0" prefixed icons.
00,01,02,03,04,05,06,07,08,09.png
Ill look into it again when i get a chance.
something going on casting to string.
I would just change the icon names but  that makes 00.png kinda of weird...

**Comment by cytech** [comment]
ok, i just added copies with the truncated name (per closed PR#30)
hopefully this takes care of it.
maybe a problem with 0.png (if anybody has a tornado in their forecast...)
