### ISSUE TITLE
HASSIO or Supervised Install

### ISSUE THREAD

**Issue by chrismdann** [cytech/Home-Assistant-wundergroundpws#52]
It appears you changed the file which you used to change on line 45 from Homeassistant to Config for Hassio installs.  That line is gone.  Do you now change the Homeassistant. starting on line 16 to Config?

**Comment by cytech** [comment]
the change was made so you should not have to edit sensor.py anymore

**Comment by chrismdann** [comment]
There doesn't seem to be a way to integrate forecasting.
