### ISSUE TITLE
Suggested change not in sensor.py file.

### ISSUE THREAD

**Issue by chrismdann** [cytech/Home-Assistant-wundergroundpws#53]
Your suggested change I'm pasting below has one issue.  The new sensor.py file doesn't have the stated line 45 or 46 you describe needing to be changed.  That has been removed.  Should I paste that in the file again?

I created this to work with my Home Assistant Setup which is Home Assistant Core in a venv on a Raspberry Pi.
This fails on other types of Home Assistant installations. Per issues reported (issue #1 ), you will need to modify the sensor.py for these other installation types.

Home Assistant Operating System:

edit sensor.py in custom_components/wundergroundpws and change line 46 from

load_config = config.load_yaml_config_file(conf_file)
to

load_config = config.load_yaml_config_file('/home/homeassistant/configuration.yaml')

Home Assistant Container (Hass.IO):

edit sensor.py in custom_components/wundergroundpws and change line 46 from

load_config = config.load_yaml_config_file(conf_file)
to

load_config = config.load_yaml_config_file('/config/configuration.yaml')

Home Assistant Supervised:

???

See updated README.md

**Comment by cytech** [comment]
What suggested change?
sensor.py has been updated and the current readme is correct.
you should not have to change anything.
I also saw you are posting issues to the Home Assistant Core repo about this.
THIS is a custom integration and is not supported by home assistant.

**Comment by chrismdann** [comment]
Does it work with Hassio or just the Docker install with homeassistant directory instead of config?

**Comment by chrismdann** [comment]
Fixed.

**Comment by chrismdann** [comment]
fixed
