### ISSUE TITLE
problem ??

### ISSUE THREAD

**Issue by belidi** [cytech/Home-Assistant-wundergroundpws#54]
I have this problem since qlq update:

Invalid config for [sensor.wundergroundpws]: required key not provided @ data['numeric_precision']. Got None. (See ?, line ?).

in config.yml  : - platform: wundergroundpws
    api_key : XXXXXXXXXXXXXXXXXX
    pws_id : IRGIONWA31
    monitored_conditions:
      - dewpt
      - windGust
      - precipTotal
      - windChill
      - uv
      - solarRadiation
      - temp
      - humidity

**Comment by cytech** [comment]
see README
UPGRADE NOTE: numeric_precision must be added to your exisiting configuration.yaml for this sensor. This adds the ability to display PWS data as integer or decimal. Valid options are 'none' or 'decimal'. See example below.
- platform: wundergroundpws
    api_key: YOUR_API_KEY
    pws_id: YOUR_STATION_ID
    numeric_precision: none

**Comment by belidi** [comment]
ok ... :-) thank Y

**Comment by belidi** [comment]
if I place, as is, explained in the read me, the following elements, I have this error, (my config:
    
       - weather_3d
       - weather_3n
       - weather_4d
       - weather_4n
    daily_forecast:
    name: Daily Forecast
    entities:
       - sensor.wupws_weather_1d
       - sensor.wupws_weather_1n
       - sensor.wupws_weather_2d             )
       
      - invalid config for [sensor.wundergroundpws]: [daily_forecast] is an invalid option for [sensor.wundergroundpws]. Check: sensor.wundergroundpws->daily_forecast. (See ?, line ?).

**Comment by cytech** [comment]
remove

daily_forecast:
name: Daily Forecast
entities:
   - sensor.wupws_weather_1d
   - sensor.wupws_weather_1n
   - sensor.wupws_weather_2d     

from your config

that is an example of the entities created from the monitored conditions.
you will enter those sensors when you create a forecast card in HA

**Comment by Ebdirtrider** [comment]
Have same issue since new install.  
if i insert numeric_precision I recieve " Invalid config for [sensor.wundergroundpws]: [numeric_precision] is an invalid option for [sensor.wundergroundpws]. Check: sensor.wundergroundpws->numeric_precision. (See ?, line ?). " when checking config in home assistant. 
but if i remove it works kinda,

**Comment by cytech** [comment]
you need to pull the entire module down and install
there are changes to sensor.py, icons, etc.
you can't just add numeric_precision to the old custom integration
