### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by gokuro** [cytech/Home-Assistant-wundergroundpws#57]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 6:36:19 AM (2 occurrences)
Last logged: 6:36:35 AM

No 'version' key in the manifest file for custom integration 'wundergroundpws'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'wundergroundpws'
No 'version' key in the manifest file for custom integration 'shelly'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'shelly'

**Comment by cytech** [comment]
fixed #56
