### ISSUE TITLE
 error in manifest.json file

### ISSUE THREAD

**Issue by pollinolas** [cytech/Home-Assistant-wundergroundpws#58]
first thing, thanks for your work,
after update to 0.2.0 version the following error appears:

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/integration.py:88
Integration: HACS (documentation, issues)
First occurred: 16:16:33 (1 occurrences)
Last logged: 16:16:33

<Integration cytech/Home-Assistant-wundergroundpws> Could not read manifest.json [Expecting property name enclosed in double quotes: line 12 column 1 (char 331)]

**Comment by cytech** [comment]
sorry extra comma....
fixed v0.2.1
