### ISSUE TITLE
No version key in the manifest file

### ISSUE THREAD

**Issue by davewatson91** [cytech/Home-Assistant-wundergroundpws#62]
Home Assistant 2021.4 log

No 'version' key in the manifest file for custom integration 'wundergroundpws'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'wundergroundpws'

**Comment by cytech** [comment]
make sure you have installed the latest release 0.2.1

**Comment by rpitera** [comment]
I downloaded it but hadn't gotten a chance to install it.  But I just checked and the version is in the manifest - thanks!

**Comment by davewatson91** [comment]
Apologies, I clearly missed the update!
