### ISSUE TITLE
No ‘version’ key in the manifest 

### ISSUE THREAD

**Issue by rjkrom** [cytech/Home-Assistant-wundergroundpws#64]
No ‘version’ key in the manifest will make this integration stop working in the next release 2021.6, if I understand correctly. 
Is somebody capable of updating this integration? I’m using it every day.

Please refer to the change log via https://github.com/home-assistant/core/pull/49726

===

Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/init.py so you can add custom_components/awesome/manifest.json to it.

For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest

Custom integrations that do not have this will be blocked from loading if it’s missing a version in the manifest starting with Home Assistant 2021.6.

If you see these errors, please report the issue with the author of that custom integration.

**Comment by rpitera** [comment]
You need to look at the latest version of the code in the repo.  You'll see it has the updated manifest.json already.

**Comment by rjkrom** [comment]
Thanks a lot! I overlooked it apparently.

**Comment by rpitera** [comment]
No worries!  Glad to help.
