### ISSUE TITLE
Add Version Number

### ISSUE THREAD

**Issue by chrismdann** [cytech/Home-Assistant-wundergroundpws#66]
As of 2021.6 the version number needs to be added.

**Comment by upwindanderl** [comment]
`2021-06-25 10:40:39 ERROR (SyncWorker_5) [homeassistant.loader] The custom integration 'wundergroundpws' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

without version key this addon is not usable over hacs or custom components

**Comment by cytech** [comment]
make sure you hae the latest release of this custom component installed, v0.2.1.
This was implemented back in March

**Comment by upwindanderl** [comment]
ouh yeah
i do :) 

![grafik](https://user-images.githubusercontent.com/51791206/123430585-a5fe1600-d5c8-11eb-915c-760434a0838d.png)

but after reboot this is happening here 
![grafik](https://user-images.githubusercontent.com/51791206/123430813-e65d9400-d5c8-11eb-9ad7-1f4612addc37.png)
