### ISSUE TITLE
Broken in new HA

### ISSUE THREAD

**Issue by interbiznw** [cytech/Home-Assistant-wundergroundpws#69]
This is now broken after my HA updated to version  core-2021.7.3

<html>
<body>

Version | core-2021.7.3
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.9.5
Operating System Family | Linux
Operating System Version | 5.10.17-v7

</body>
</html>

I now get the following error when checking config or try to restart:

Configuration invalid
Platform error sensor.wundergroundpws - Integration 'wundergroundpws' not found.

i have to completely remove the 'wundergroundpws' sensor from my config to get my HA to function correctly

**Comment by stefferber** [comment]
Can confirm for core versions 2021.6.1-20217.4 after upgrading from 2021.5.5

**Comment by stefferber** [comment]
Today, I updated the `wundergroundpws` files to the newest version in the folder `/config/custom_components/wundergroundpws` and the icons in `/config/www/wupws_icons` ,but the error message prevents HA to restart. Looks like HA is not allowing to load additional integrations:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:535
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:43:40 (1 occurrences)
Last logged: 15:43:40

[547296208928] The system cannot restart because the configuration is not valid: Platform error sensor.wundergroundpws - Integration 'wundergroundpws' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 535, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.wundergroundpws - Integration 'wundergroundpws' not found.
```
Any hints?

**Comment by cytech** [comment]
Integration 'wundergroundpws' not found. seems to be the key here...
i am running 2021.7.4 in a venv and have no problems.
has something changed in home assistant core as to where it looks for custom integrations?

**Comment by stefferber** [comment]
Agree with you. I looked through the  [release notes of HA](https://www.home-assistant.io/blog/2021/07/07/release-20217/ ) but could not find something; but of course that does not mean a lot as I could easliy missed it:

**Comment by stefferber** [comment]
I got something similar here [version key need to exist containing a valid version](https://community.home-assistant.io/t/configuration-component-error-not-found/313577)
`Starting with Home Assistant 2021.6 all custom integrations (the folders (directories) that you have under the custom_components folder in your configuration directory) needs to have a manifest.json file, and in the file a version key need to exist containing a valid version. If this is not present, the integration will not be loaded, and you will see logs like`

**Comment by interbiznw** [comment]
Yep, adding the version fixed it for me
