### ISSUE TITLE
Units not partly not shown

### ISSUE THREAD

**Issue by hirschy81** [cytech/Home-Assistant-wundergroundpws#70]
After upgrading to version 0.2.1 some units for various sensors are missing (see screenshot) (instead, the unit-reference number is shown)

![image](https://user-images.githubusercontent.com/63389792/127881712-f6e4fd04-fbb8-4164-b8a9-c63c379ce150.png)

**Comment by cytech** [comment]
fixed v0.8.0
REQUIRES HOME ASSISTANT V 2021.8 OR LATER !!
