### ISSUE TITLE
Integration 'wundergroundpws' not found

### ISSUE THREAD

**Issue by MVerBerkmoes** [cytech/Home-Assistant-wundergroundpws#73]
D/L'ed and copied the custom_components directory and the www directory as directed in the README.

Added sensor to configuration.yaml using my api_key and pws_id.

Attempted restart of HA core displays the following error window: 'The system cannot restart because the configuration is not valid: Platform error sensor.wundergroundpws - Integration 'wundergroundpws' not found.'

![explorer_lepTJtlaHE](https://user-images.githubusercontent.com/48867655/138008308-4603c257-2aa2-48d8-a924-cb10805fad6f.png)

Version | core-2021.10.6
Installation Type | Home Assistant OS

**Comment by agarridosaez** [comment]
I have done exactly the same as the MVerBerkmoes user. And it gives me the same error : 
![image](https://user-images.githubusercontent.com/5555882/143723803-7ebb949d-bc90-41a8-80b6-9fb4bf872360.png)

Any ideas?
Thank you

**Comment by aberres** [comment]
For future reference:

I had the same problem, but there should be an easy fix: First copy the files, then restart, and only then alter the configuration.

Before the reboot HA does not yet know about the integration and hence complains.

**Comment by jektvik** [comment]
This would be prudent to add to the docs.
