### ISSUE TITLE
Cannot get integration to work

### ISSUE THREAD

**Issue by MichaelRV82** [cytech/Home-Assistant-wundergroundpws#74]
I am getting this error. Any ideas?

Error fetching WUnderground data: ContentTypeError(RequestInfo(url=URL('https://api.weather.com/v2/pws/observations/current?stationId=WUNDERGROUND_STATION_ID&format=json&units=m&apiKey=WUNDERGROUND_API_KEY&numericPrecision=decimal'), method='GET', headers=<CIMultiDictProxy('Host': 'api.weather.com', 'User-Agent': 'HomeAssistant/2021.10.6 aiohttp/3.7.4.post0 Python/3.9', 'Accept-Encoding': 'gzip', 'Accept': '*/*')>, real_url=URL('https://api.weather.com/v2/pws/observations/current?stationId=WUNDERGROUND_STATION_ID&format=json&units=m&apiKey=WUNDERGROUND_API_KEY&numericPrecision=decimal')), (), message='Attempt to decode JSON with unexpected mimetype: text/html', headers=<CIMultiDictProxy('Content-Type': 'text/html', 'Content-Length': '133', 'Expires': 'Mon, 01 Nov 2021 10:23:59 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 01 Nov 2021 10:23:59 GMT', 'Connection': 'keep-alive', 'Content-Security-Policy': "default-src 'none'", 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=86400')>)

**Comment by cytech** [comment]
you have not set your station_id or API key
