### ISSUE TITLE
Crashes HASSIO version 0.96.4

### ISSUE THREAD

**Issue by Haringstad** [cytech/Home-Assistant-wundergroundpws#8]
This breaks HASSIO in Docker on Raspberry PI, already from 0.92. I'm sorry, but I don't have time to really trace the issue. But I hope you fix this!

**Comment by cytech** [comment]
Sorry
I also don't have time and am not running HassIO in docker on PI

**Comment by Haringstad** [comment]
Good to know, and thank you for your effort.

**Comment by interbiznw** [comment]
@Haringstad It crashes due to it looking for the config dir in the wrong spot and not finding the configuration.yaml

**Comment by Haringstad** [comment]
I'ts already fixed @interbiznw :-)

**Comment by interbiznw** [comment]
@Haringstad Oh, Odd.. I grabbed the code the other day and still had that issue, and had to change the line for the config file to get it working
