### ISSUE TITLE
WARNING: Sensors implement device_state_attributes 

### ISSUE THREAD

**Issue by garyak** [cytech/Home-Assistant-wundergroundpws#82]
Warning:

`2021-12-25 07:02:03 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.wupws_weather_3n (<class 'custom_components.wundergroundpws.sensor.WUndergroundSensor'>) implements device_state_attributes. Please report it to the custom component author.`

Latest versions of HA Core, Supervisor, and OS.

**Comment by cytech** [comment]
update to v 0.8.1
