### ISSUE TITLE
Option to make station ID part of entity names.

### ISSUE THREAD

**Issue by rct** [cytech/Home-Assistant-wundergroundpws#83]
Enhancement request - if you do have more than one station (accidentally or intentionally) it is difficult to tell which station the entities belong to.  

First thought is station ID should be one of the attributes of the entities, just like date is an attribute. 

On the other hand, if there was just an option to make the station ID be part of the entity names, that would remove ambiguity and probably handle a number of use cases, including changing stations.

**Comment by Flop2006** [comment]
Could you give me a hint on how to view data from more than one weather station?

**Comment by cytech** [comment]
added v2.0.1
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v2.X.X
