### ISSUE TITLE
stop working with HA 2022.3

### ISSUE THREAD

**Issue by fcasarramona** [cytech/Home-Assistant-wundergroundpws#93]
After upgrading to HA core 2022.3 all sensors are in gray and shown as unavailable.

¿Any one with the same issue?

I found no relevant log message.

If downgrading to 2022.2.9, works again.

**Comment by cytech** [comment]
duplicate #89 #92 
you need to make sure you have installed the latest wupws custom component release
0.8.1

**Comment by fcasarramona** [comment]
You are right. Sorry.
